### ISSUE TITLE
IllegalArgumentException thrown when trying to add inline comment.

### ISSUE THREAD

**Issue by Reasno** [nhat-phan/merge-request-integration#104]
```java
java.lang.IllegalArgumentException: position[start_sha] cannot be empty or null
	at org.gitlab4j.api.GitLabApiForm.withParam(GitLabApiForm.java:192)
	at org.gitlab4j.api.DiscussionsApi.createMergeRequestDiscussion(DiscussionsApi.java:319)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.requestHandler.GitlabCreateNoteRequestHandler$handle$1.invoke(GitlabCreateNoteRequestHandler.kt:16)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.requestHandler.GitlabCreateNoteRequestHandler$handle$1.invoke(GitlabCreateNoteRequestHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabClient$Companion.invoke(GitlabClient.kt:32)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.requestHandler.GitlabCreateNoteRequestHandler.handle(GitlabCreateNoteRequestHandler.kt:30)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.requestHandler.GitlabCreateNoteRequestHandler.handle(GitlabCreateNoteRequestHandler.kt:11)
	at net.ntworld.foundation.RequestHandler$DefaultImpls.execute(RequestHandler.kt:7)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.requestHandler.GitlabCreateNoteRequestHandler.execute(GitlabCreateNoteRequestHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.requestHandler.GitlabCreateNoteRequestHandler.execute(GitlabCreateNoteRequestHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.LocalServiceBus.process(LocalServiceBus.kt:70)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi.createPositionComment(GitlabCommentApi.kt:112)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi.create(GitlabCommentApi.kt:76)
	at net.ntworld.mergeRequestIntegration.requestHandler.CreateCommentRequestHandler.handle(CreateCommentRequestHandler.kt:19)
	at net.ntworld.mergeRequestIntegration.requestHandler.CreateCommentRequestHandler.handle(CreateCommentRequestHandler.kt:12)
	at net.ntworld.foundation.RequestHandler$DefaultImpls.execute(RequestHandler.kt:7)
	at net.ntworld.mergeRequestIntegration.requestHandler.CreateCommentRequestHandler.execute(CreateCommentRequestHandler.kt:12)
	at net.ntworld.mergeRequestIntegration.requestHandler.CreateCommentRequestHandler.execute(CreateCommentRequestHandler.kt:12)
	at net.ntworld.mergeRequestIntegration.LocalServiceBus.process(LocalServiceBus.kt:70)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl.onCreateCommentRequested(DiffPresenterImpl.kt:148)
	at jdk.internal.reflect.GeneratedMethodAccessor416.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:123)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:86)
	at com.sun.proxy.$Proxy180.onCreateCommentRequested(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView$myThreadPresenterEventListener$1.onCreateCommentRequested(AbstractDiffView.kt:68)
	at jdk.internal.reflect.GeneratedMethodAccessor415.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:123)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:86)
	at com.sun.proxy.$Proxy188.onCreateCommentRequested(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.component.thread.ThreadPresenterImpl$myThreadViewActionListener$1.onCreateCommentRequested(ThreadPresenterImpl.kt:33)
	at jdk.internal.reflect.GeneratedMethodAccessor414.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:123)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:86)
	at com.sun.proxy.$Proxy187.onCreateCommentRequested(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.component.thread.ThreadViewImpl$myEditorComponentEventListener$1.onSubmitClicked(ThreadViewImpl.kt:101)
	at jdk.internal.reflect.GeneratedMethodAccessor413.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:123)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:86)
	at com.sun.proxy.$Proxy185.onSubmitClicked(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.component.comment.EditorComponentImpl$MyAddCommentAction.actionPerformed(EditorComponentImpl.kt:69)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:276)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:155)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:439)
	at java.desktop/java.awt.Component.processEvent(Component.java:6415)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5025)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:967)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:904)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:503)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by PeskovV** [comment]
Same issue for me

**Comment by PeskovV** [comment]
I think there is relationship between this issue and #93
