### ISSUE TITLE
Incompatible with Markdown Navigator Enhanced

### ISSUE THREAD

**Issue by metalbote** [nhat-phan/merge-request-integration#123]
Plugin doesnot work if [Markdown Navigator enhanced](https://plugins.jetbrains.com/plugin/7896-markdown-navigator-enhanced) is active.

Cannot open MR, quitting with following bug report:

`com.intellij.diagnostic.ImplementationConflictException: Language of 'class net.ntworld.mergeRequestIntegrationIde.util.FileTypeUtil$MarkdownLanguage' is already registered: Language: Markdown
	at com.intellij.lang.Language.<init>(Language.java:79)
	at com.intellij.lang.Language.<init>(Language.java:60)
	at net.ntworld.mergeRequestIntegrationIde.util.FileTypeUtil$MarkdownLanguage.<init>(FileTypeUtil.kt:8)
	at net.ntworld.mergeRequestIntegrationIde.util.FileTypeUtil.getLanguage(FileTypeUtil.kt:32)
	at net.ntworld.mergeRequestIntegrationIde.util.FileTypeUtil.access$getLanguage(FileTypeUtil.kt:7)
	at net.ntworld.mergeRequestIntegrationIde.util.FileTypeUtil$markdownFileType$2.invoke(FileTypeUtil.kt:26)
	at net.ntworld.mergeRequestIntegrationIde.util.FileTypeUtil$markdownFileType$2.invoke(FileTypeUtil.kt:7)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.ntworld.mergeRequestIntegrationIde.util.FileTypeUtil.getMarkdownFileType(FileTypeUtil.kt)
	at net.ntworld.mergeRequestIntegrationIde.component.comment.EditorComponentImpl$myEditorTextField$2.invoke(EditorComponentImpl.kt:43)
	at net.ntworld.mergeRequestIntegrationIde.component.comment.EditorComponentImpl$myEditorTextField$2.invoke(EditorComponentImpl.kt:21)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.ntworld.mergeRequestIntegrationIde.component.comment.EditorComponentImpl.getMyEditorTextField(EditorComponentImpl.kt)
	at net.ntworld.mergeRequestIntegrationIde.component.comment.EditorComponentImpl.<init>(EditorComponentImpl.kt:153)
	at net.ntworld.mergeRequestIntegrationIde.component.comment.CommentComponentFactoryImpl.makeEditor(CommentComponentFactoryImpl.kt:62)
	at net.ntworld.mergeRequestIntegrationIde.mergeRequest.comments.CommentsTabViewImpl$myMainEditor$2.invoke(CommentsTabViewImpl.kt:95)
	at net.ntworld.mergeRequestIntegrationIde.mergeRequest.comments.CommentsTabViewImpl$myMainEditor$2.invoke(CommentsTabViewImpl.kt:29)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.ntworld.mergeRequestIntegrationIde.mergeRequest.comments.CommentsTabViewImpl.getMyMainEditor(CommentsTabViewImpl.kt)
	at net.ntworld.mergeRequestIntegrationIde.mergeRequest.comments.CommentsTabViewImpl.<init>(CommentsTabViewImpl.kt:162)
	at net.ntworld.mergeRequestIntegrationIde.mergeRequest.comments.CommentsTabFactory.makeCommentsTabView(CommentsTabFactory.kt:12)
	at net.ntworld.mergeRequestIntegrationIde.ui.mergeRequest.MergeRequestDetails$myCommentsTabPresenter$2.invoke(MergeRequestDetails.kt:65)
	at net.ntworld.mergeRequestIntegrationIde.ui.mergeRequest.MergeRequestDetails$myCommentsTabPresenter$2.invoke(MergeRequestDetails.kt:25)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.ntworld.mergeRequestIntegrationIde.ui.mergeRequest.MergeRequestDetails.getMyCommentsTabPresenter(MergeRequestDetails.kt)
	at net.ntworld.mergeRequestIntegrationIde.ui.mergeRequest.MergeRequestDetails.<init>(MergeRequestDetails.kt:157)
	at net.ntworld.mergeRequestIntegrationIde.ui.toolWindowTab.MergeRequestToolWindowTab.<init>(MergeRequestToolWindowTab.kt:24)
	at net.ntworld.mergeRequestIntegrationIde.ui.toolWindowTab.HomeToolWindowTab.openTab(HomeToolWindowTab.kt:141)
	at net.ntworld.mergeRequestIntegrationIde.ui.toolWindowTab.HomeToolWindowTab.access$openTab(HomeToolWindowTab.kt:22)
	at net.ntworld.mergeRequestIntegrationIde.ui.toolWindowTab.HomeToolWindowTab$myDetailsListEventListener$1.mergeRequestSelected(HomeToolWindowTab.kt:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:123)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:86)
	at com.sun.proxy.$Proxy225.mergeRequestSelected(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.ui.provider.ProviderDetails$myListEventListener$1.mergeRequestSelected(ProviderDetails.kt:38)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:123)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:86)
	at com.sun.proxy.$Proxy225.mergeRequestSelected(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.ui.provider.ProviderDetailsMRList$myListMouseListener$1.mouseClicked(ProviderDetailsMRList.kt:52)
	at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6655)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4556)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:911)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by ll14m4n** [comment]
@metalbote I have the same issue. Did you find any solution/workaround ?

**Comment by metalbote** [comment]
nothing, and did not have the time to investigate/solve on my own
