### ISSUE TITLE
com.intellij.openapi.vcs.VcsException: bad object

### ISSUE THREAD

**Issue by cypressious** [nhat-phan/merge-request-integration#127]
Just got the following exception running the latest version of EE on 

IntelliJ IDEA 2020.3.1 (Ultimate Edition)
Build #IU-203.6682.168, built on December 29, 2020
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: compiler.automake.allow.when.app.running=true
Non-Bundled Plugins: dev.meanmail.plugin.nginx-intellij-plugin, com.failfast, net.ntworld.nhat-phan.merge-request-integration-ee, patrick.kelleter.angular-cli-quick-switch, String Manipulation, com.jetbrains.codeWithMe, org.jetbrains.kotlin

```
com.intellij.openapi.vcs.VcsException: bad object 134498659bd13f5fd2b549f0d80ccd07bf10ccf1
	at git4idea.commands.GitCommandResult.throwOnError(GitCommandResult.java:152)
	at git4idea.history.GitDetailsCollector.readRecordsFromHandler(GitDetailsCollector.kt:95)
	at git4idea.history.GitDetailsCollector.readFullDetailsFromHandler(GitDetailsCollector.kt:70)
	at git4idea.history.GitDetailsCollector.readFullDetailsForHashes(GitDetailsCollector.kt:44)
	at git4idea.history.GitLogUtil.readFullDetailsForHashes(GitLogUtil.java:209)
	at git4idea.log.GitLogProvider.readFullDetails(GitLogProvider.java:333)
	at com.intellij.vcs.log.util.VcsLogUtil.getDetails(VcsLogUtil.java:213)
	at net.ntworld.mergeRequestIntegrationIde.infrastructure.service.repositoryFile.LocalRepositoryFileService.findChanges(LocalRepositoryFileService.kt:35)
	at net.ntworld.mergeRequestIntegrationIde.infrastructure.service.repositoryFile.RepositoryFileDecorator.findChanges(RepositoryFileDecorator.kt:13)
	at net.ntworld.mergeRequestIntegrationIde.infrastructure.service.repositoryFile.CachedRepositoryFile.access$findChanges$s645213640(CachedRepositoryFile.kt:10)
	at net.ntworld.mergeRequestIntegrationIde.infrastructure.service.repositoryFile.CachedRepositoryFile$findChanges$1.invoke(CachedRepositoryFile.kt:20)
	at net.ntworld.mergeRequestIntegrationIde.infrastructure.service.repositoryFile.CachedRepositoryFile$findChanges$1.invoke(CachedRepositoryFile.kt:10)
	at net.ntworld.mergeRequest.api.Cache$DefaultImpls.getOrRun(Cache.kt:28)
	at net.ntworld.mergeRequestIntegration.provider.MemoryCache.getOrRun(MemoryCache.kt:11)
	at net.ntworld.mergeRequestIntegrationIde.infrastructure.service.repositoryFile.CachedRepositoryFile.findChanges(CachedRepositoryFile.kt:18)
	at net.ntworld.mergeRequestIntegrationIde.ui.mergeRequest.tab.commit.CommitChanges$setCommits$1.invoke(CommitChanges.kt:79)
	at net.ntworld.mergeRequestIntegrationIde.ui.mergeRequest.tab.commit.CommitChanges$setCommits$1.invoke(CommitChanges.kt:25)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by HanSolo80** [comment]
I got the same error every time I select a merge request and click on "Code Review" Button.
The IDE then doesn't show any changes and I cannot do anything in this view unless I leave "Code Review" state.

**Comment by dozer47528** [comment]
same problem

**Comment by oers** [comment]
same problem, happens very frequently
can't properly review the code

**Comment by jessevitrone** [comment]
I'm getting the same issue, it has made the plugin completely unusable
