### ISSUE TITLE
Extension not working with the following exception

### ISSUE THREAD

**Issue by ItamarShDev** [nhat-phan/merge-request-integration#130]
EE edition
Latest PyCharm
Self Hosted, VPN masked Gitlab 13.6
Connection in settings is OK

This is happening when using integrated tool to create MRs.
The MRs are created with no description, and it breaks the extension

```
java.lang.IllegalStateException: input.description must not be null
	at net.ntworld.mergeRequestIntegration.provider.gitlab.transformer.GitlabMRSimpleTransformer.transform(GitlabMRSimpleTransformer.kt:18)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabMergeRequestApi.search(GitlabMergeRequestApi.kt:120)
	at net.ntworld.mergeRequestIntegration.provider.MergeRequestApiDecorator.search(MergeRequestApiDecorator.kt)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabMergeRequestApiCache.search(GitlabMergeRequestApiCache.kt:38)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.handle(GetMergeRequestsQueryHandler.kt:17)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.handle(GetMergeRequestsQueryHandler.kt:11)
	at net.ntworld.foundation.cqrs.QueryHandler$DefaultImpls.execute(QueryHandler.kt:10)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.execute(GetMergeRequestsQueryHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.execute(GetMergeRequestsQueryHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.LocalQueryBus.process(LocalQueryBus.kt:38)
	at net.ntworld.mergeRequestIntegrationIde.task.SearchMergeRequestTask.run(SearchMergeRequestTask.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Pirozek** [comment]
+1 having almost the same exception, cant list any MRs, that are not mine

```java.lang.IllegalStateException: input.description must not be null
	at net.ntworld.mergeRequestIntegration.provider.gitlab.transformer.GitlabMRSimpleTransformer.transform(GitlabMRSimpleTransformer.kt:18)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabMergeRequestApi.search(GitlabMergeRequestApi.kt:120)
	at net.ntworld.mergeRequestIntegration.provider.MergeRequestApiDecorator.search(MergeRequestApiDecorator.kt)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabMergeRequestApiCache.search(GitlabMergeRequestApiCache.kt:38)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.handle(GetMergeRequestsQueryHandler.kt:17)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.handle(GetMergeRequestsQueryHandler.kt:11)
	at net.ntworld.foundation.cqrs.QueryHandler$DefaultImpls.execute(QueryHandler.kt:10)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.execute(GetMergeRequestsQueryHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.execute(GetMergeRequestsQueryHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.LocalQueryBus.process(LocalQueryBus.kt:38)
	at net.ntworld.mergeRequestIntegrationIde.task.SearchMergeRequestTask.run(SearchMergeRequestTask.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
