### ISSUE TITLE
got this exception pycharm 2020.3 

### ISSUE THREAD

**Issue by michaelpecan** [nhat-phan/merge-request-integration#139]
java.lang.Exception: java.net.UnknownHostException: gitlab.aws.pecan.ai
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi$getAll$response$1.invoke(GitlabCommentApi.kt:34)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi$getAll$response$1.invoke(GitlabCommentApi.kt:19)
	at net.ntworld.foundation.internal.ServiceBusProcessResultImpl.ifError(ServiceBusProcessResultImpl.kt:18)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi.getAll(GitlabCommentApi.kt:33)
	at net.ntworld.mergeRequestIntegration.provider.DraftCommentApi.getAll(DraftCommentApi.kt:12)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetCommentsQueryHandler.handle(GetCommentsQueryHandler.kt:18)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetCommentsQueryHandler.handle(GetCommentsQueryHandler.kt:11)
	at net.ntworld.foundation.cqrs.QueryHandler$DefaultImpls.execute(QueryHandler.kt:10)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetCommentsQueryHandler.execute(GetCommentsQueryHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetCommentsQueryHandler.execute(GetCommentsQueryHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.LocalQueryBus.process(LocalQueryBus.kt:38)
	at net.ntworld.mergeRequestIntegrationIde.task.GetCommentsTask.run(GetCommentsTask.kt:32)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by bojanbg** [comment]
I'm experiencing the same thing with PyCharm 2021.1.1. I'm using version `2020.3.0-built-for-ide-2021.1.x` of the plugin.
