### ISSUE TITLE
SimpleDiffViewer.getSyncScrollSupport must not return null

### ISSUE THREAD

**Issue by ul1tka** [nhat-phan/merge-request-integration#140]
Plugin version 2020.3.0-built-for-ide-2020.3.x in CLion 2020.3.2, constantly getting the following exception:

```
java.lang.IllegalStateException: @NotNull method com/intellij/diff/tools/simple/SimpleDiffViewer.getSyncScrollSupport must not return null
	at com.intellij.diff.tools.simple.SimpleDiffViewer.$$$reportNull$$$0(SimpleDiffViewer.java)
	at com.intellij.diff.tools.simple.SimpleDiffViewer.getSyncScrollSupport(SimpleDiffViewer.java:358)
	at net.ntworld.mergeRequestIntegrationIde.diff.TwoSideTextDiffView.calcPositionEditor2(TwoSideTextDiffView.kt:138)
	at net.ntworld.mergeRequestIntegrationIde.diff.TwoSideTextDiffView.initializeByLogicalLine(TwoSideTextDiffView.kt:41)
	at net.ntworld.mergeRequestIntegrationIde.diff.TwoSideTextDiffView.initializeLine(TwoSideTextDiffView.kt:50)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl.handleWhenCommentsGetUpdated(DiffPresenterImpl.kt:111)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl.access$handleWhenCommentsGetUpdated(DiffPresenterImpl.kt:36)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl$onCommentsUpdated$1.run(DiffPresenterImpl.kt:92)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by jkuchar** [comment]
The same problem here! with PhpStorm 2021.1.1 (plugin version 2020.3.0-buit-for-ide-2021.1.x).

```
java.lang.IllegalStateException: @NotNull method com/intellij/diff/tools/simple/SimpleDiffViewer.getSyncScrollSupport must not return null
	at com.intellij.diff.tools.simple.SimpleDiffViewer.$$$reportNull$$$0(SimpleDiffViewer.java)
	at com.intellij.diff.tools.simple.SimpleDiffViewer.getSyncScrollSupport(SimpleDiffViewer.java:359)
	at net.ntworld.mergeRequestIntegrationIde.diff.TwoSideTextDiffView.calcPositionEditor2(TwoSideTextDiffView.kt:138)
	at net.ntworld.mergeRequestIntegrationIde.diff.TwoSideTextDiffView.initializeByLogicalLine(TwoSideTextDiffView.kt:41)
	at net.ntworld.mergeRequestIntegrationIde.diff.TwoSideTextDiffView.initializeLine(TwoSideTextDiffView.kt:50)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl.handleWhenCommentsGetUpdated(DiffPresenterImpl.kt:111)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl.access$handleWhenCommentsGetUpdated(DiffPresenterImpl.kt:36)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl$onCommentsUpdated$1.run(DiffPresenterImpl.kt:92)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by rainmote** [comment]
I found the reason, this error will be generated after closing the diff view
Repair method:
Add at the beginning of the function `initializeByLogicalLine` in the file `TwoSideTextDiffView.kt`
```
if (viewer.isDisposed()) {
    return
}
```
