### ISSUE TITLE
IDE Fatal Errors

### ISSUE THREAD

**Issue by mfournarakis** [nhat-phan/merge-request-integration#147]
I'm having issues with latest version of PyCharm

![Screenshot 2021-05-10 at 15 29 40](https://user-images.githubusercontent.com/33094229/117659440-9ce5f080-b1a4-11eb-8e87-5e8c92f0655a.png)

**Comment by nessor** [comment]
Also having problems with PHPStrom and WebStrom with the EE. Stacktrace from PHPStrom:

```
java.lang.Exception: java.net.SocketTimeoutException: Read timed out
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi$getAll$response$1.invoke(GitlabCommentApi.kt:34)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi$getAll$response$1.invoke(GitlabCommentApi.kt:19)
	at net.ntworld.foundation.internal.ServiceBusProcessResultImpl.ifError(ServiceBusProcessResultImpl.kt:18)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi.getAll(GitlabCommentApi.kt:33)
	at net.ntworld.mergeRequestIntegration.provider.DraftCommentApi.getAll(DraftCommentApi.kt:12)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetCommentsQueryHandler.handle(GetCommentsQueryHandler.kt:18)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetCommentsQueryHandler.handle(GetCommentsQueryHandler.kt:11)
	at net.ntworld.foundation.cqrs.QueryHandler$DefaultImpls.execute(QueryHandler.kt:10)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetCommentsQueryHandler.execute(GetCommentsQueryHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetCommentsQueryHandler.execute(GetCommentsQueryHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.LocalQueryBus.process(LocalQueryBus.kt:38)
	at net.ntworld.mergeRequestIntegrationIde.task.GetCommentsTask.run(GetCommentsTask.kt:32)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by schegi** [comment]
Same as @mariosfourn with GoLand on OSX.

**Comment by mfournarakis** [comment]
Hi, is this going to be fixed? I have the EE version and this wait is not acceptable. I'll have to ask for end the subscription
