### ISSUE TITLE
Cannot do Code Review on Android Studio

### ISSUE THREAD

**Issue by LionZXY** [nhat-phan/merge-request-integration#17]
I can't press on button `Code Review` in Android Studio Canary 9.
I use Merge Request Integration EE - Code Review for GitLab and buy plugin
```
java.lang.Throwable: Assertion failed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:180)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:189)
	at org.jetbrains.ide.BuiltInServerManagerImpl.waitForStart(BuiltInServerManagerImpl.kt:110)
	at org.jetbrains.git4idea.ssh.GitXmlRpcHandlerService.getXmlRcpPort(GitXmlRpcHandlerService.java:69)
	at git4idea.commands.GitHandlerAuthenticationManager.prepareNativeSshAuth(GitHandlerAuthenticationManager.java:212)
	at git4idea.commands.GitHandlerAuthenticationManager.lambda$prepare$0(GitHandlerAuthenticationManager.java:73)
	at git4idea.GitUtil.tryRunOrClose(GitUtil.java:1081)
	at git4idea.commands.GitHandlerAuthenticationManager.prepare(GitHandlerAuthenticationManager.java:67)
	at git4idea.commands.GitImplBase.run(GitImplBase.java:153)
	at git4idea.commands.GitImplBase.runCommandWithoutCollectingOutput(GitImplBase.java:92)
	at git4idea.history.GitDetailsCollector.readRecordsFromHandler(GitDetailsCollector.kt:95)
	at git4idea.history.GitDetailsCollector.readFullDetailsFromHandler(GitDetailsCollector.kt:70)
	at git4idea.history.GitDetailsCollector.readFullDetailsForHashes(GitDetailsCollector.kt:44)
	at git4idea.history.GitLogUtil.readFullDetailsForHashes(GitLogUtil.java:219)
	at git4idea.log.GitLogProvider.readFullDetails(GitLogProvider.java:331)
	at com.intellij.vcs.log.util.VcsLogUtil.getDetails(VcsLogUtil.java:206)
	at net.ntworld.mergeRequestIntegrationIde.ui.service.DisplayChangesService.findChanges(DisplayChangesService.kt:132)
	at net.ntworld.mergeRequestIntegrationIde.ui.mergeRequest.tab.commit.CommitChanges$setCommits$1.run(CommitChanges.kt:48)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by LionZXY** [comment]
Android Studio 4.0 Canary 9  Build #AI-193.5233.102.40.6137316 
JDK: 1.8.0_212-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
OS: Mac OS X

**Comment by nhat-phan** [comment]
Hi @LionZXY,

This is git4idea plugin problem. It also happens on Intellij IDEA 2019.3.0 while I develop the plugin (fixed on Intellij IDEA 2019.3.2). In my experience it doesn't affect the Code Review button functionality. 

Could you please checkout the source branch manually then click "Code Review". If it works, problem is the plugin cannot checkout source branch or fetch from remotes, there is [an issue](https://github.com/nhat-phan/merge-request-integration/issues/13) already.

**Comment by LionZXY** [comment]
Two branch already be local

**Comment by nhat-phan** [comment]
Oops, could you please check is there any other error?

<img width="379" alt="Screen Shot 2020-01-24 at 23 45 15" src="https://user-images.githubusercontent.com/34987391/73086683-a726a180-3f03-11ea-9de5-7d1d368e582e.png">

Thank you for reporting!

**Comment by LionZXY** [comment]
Studio core:
```
com.intellij.serialization.SerializationException: Cannot deserialize parameter value (fieldName=myAndroidProject, binding=com.intellij.serialization.PolymorphicBinding@23d107e3, valueType=STRUCT, beanClass=com.android.tools.idea.gradle.project.model.AndroidModuleModel)
	at com.intellij.serialization.BeanBinding.createUsingCustomConstructor(BeanBinding.kt:135)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:204)
	at com.intellij.serialization.PolymorphicBinding.doDeserialize(PolymorphicBinding.kt:53)
	at com.intellij.serialization.PolymorphicBinding.deserialize(PolymorphicBinding.kt:19)
	at com.intellij.serialization.BeanBinding.readIntoObject(BeanBinding.kt:250)
	at com.intellij.serialization.BeanBinding.readIntoObject$default(BeanBinding.kt:222)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:217)
	at com.intellij.serialization.BaseCollectionBinding.readInto(BaseCollectionBinding.kt:31)
	at com.intellij.serialization.CollectionBinding.deserialize(CollectionBinding.kt:94)
	at com.intellij.serialization.BeanBinding.readIntoObject(BeanBinding.kt:250)
	at com.intellij.serialization.BeanBinding.readIntoObject$default(BeanBinding.kt:222)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:217)
	at com.intellij.serialization.BaseCollectionBinding.readInto(BaseCollectionBinding.kt:31)
	at com.intellij.serialization.CollectionBinding.deserialize(CollectionBinding.kt:94)
	at com.intellij.serialization.BeanBinding.readIntoObject(BeanBinding.kt:250)
	at com.intellij.serialization.BeanBinding.readIntoObject$default(BeanBinding.kt:222)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:217)
	at com.intellij.serialization.Binding$DefaultImpls.deserialize(Binding.kt:16)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:19)
	at com.intellij.serialization.BeanBinding.readIntoObject(BeanBinding.kt:250)
	at com.intellij.serialization.BeanBinding.readIntoObject$default(BeanBinding.kt:222)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:217)
	at com.intellij.serialization.BaseCollectionBinding.readInto(BaseCollectionBinding.kt:31)
	at com.intellij.serialization.CollectionBinding.deserialize(CollectionBinding.kt:30)
	at com.intellij.serialization.CollectionBinding.deserialize(CollectionBinding.kt:21)
	at com.intellij.serialization.IonObjectSerializer.doRead(IonObjectSerializer.kt:143)
	at com.intellij.serialization.IonObjectSerializer.readVersioned(IonObjectSerializer.kt:95)
	at com.intellij.serialization.VersionedFile.readAndHandleErrors(VersionedFile.kt:55)
	at com.intellij.serialization.VersionedFile.readList(VersionedFile.kt:42)
	at com.intellij.serialization.VersionedFile.readList$default(VersionedFile.kt:41)
	at com.intellij.serialization.VersionedFile.readList(VersionedFile.kt)
	at com.intellij.openapi.externalSystem.service.project.manage.ExternalProjectsDataStorage.load(ExternalProjectsDataStorage.java:377)
	at com.intellij.openapi.externalSystem.service.project.manage.ExternalProjectsDataStorage.load(ExternalProjectsDataStorage.java:84)
	at com.intellij.openapi.externalSystem.service.project.manage.ExternalProjectsManagerImpl.init(ExternalProjectsManagerImpl.java:163)
	at com.intellij.openapi.externalSystem.service.ExternalSystemStartupActivity.runActivity(ExternalSystemStartupActivity.java:19)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:216)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$null$1(StartupManagerImpl.java:177)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:396)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:388)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:68)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.serialization.SerializationException: Please annotate non-default constructor with PropertyMapping (beanClass=org.codehaus.groovy.runtime.GStringImpl)
	at com.intellij.serialization.BeanBinding.createUsingCustomConstructor(BeanBinding.kt:93)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:214)
	at com.intellij.serialization.PolymorphicBinding.doDeserialize(PolymorphicBinding.kt:53)
	at com.intellij.serialization.PolymorphicBinding.deserialize(PolymorphicBinding.kt:24)
	at com.intellij.serialization.MapBinding.read(MapBinding.kt:136)
	at com.intellij.serialization.MapBinding.readInto(MapBinding.kt:121)
	at com.intellij.serialization.MapBinding.deserialize(MapBinding.kt:98)
	at com.intellij.serialization.BeanBinding.readIntoObject(BeanBinding.kt:250)
	at com.intellij.serialization.BeanBinding.readIntoObject$default(BeanBinding.kt:222)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:217)
	at com.intellij.serialization.PolymorphicBinding.doDeserialize(PolymorphicBinding.kt:53)
	at com.intellij.serialization.PolymorphicBinding.deserialize(PolymorphicBinding.kt:19)
	at com.intellij.serialization.BeanBinding.readIntoObject(BeanBinding.kt:250)
	at com.intellij.serialization.BeanBinding.readIntoObject$default(BeanBinding.kt:222)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:217)
	at com.intellij.serialization.PolymorphicBinding.doDeserialize(PolymorphicBinding.kt:53)
	at com.intellij.serialization.PolymorphicBinding.deserialize(PolymorphicBinding.kt:19)
	at com.intellij.serialization.BeanBinding.readIntoObject(BeanBinding.kt:250)
	at com.intellij.serialization.BeanBinding.readIntoObject$default(BeanBinding.kt:222)
	at com.intellij.serialization.BeanBinding.deserialize(BeanBinding.kt:217)
	at com.intellij.serialization.PolymorphicBinding.doDeserialize(PolymorphicBinding.kt:53)
	at com.intellij.serialization.PolymorphicBinding.deserialize(PolymorphicBinding.kt:24)
	at com.intellij.serialization.BeanBinding.createUsingCustomConstructor(BeanBinding.kt:132)
	... 62 more
```
Android support:
```
java.lang.NullPointerException
	at com.android.tools.idea.diagnostics.AndroidStudioSystemHealthMonitor.getActionName(AndroidStudioSystemHealthMonitor.java:1032)
	at com.android.tools.idea.diagnostics.AndroidStudioSystemHealthMonitor.countActionInvocation(AndroidStudioSystemHealthMonitor.java:922)
	at com.android.tools.idea.diagnostics.AndroidStudioSystemHealthMonitor$6.countActionInvocation(AndroidStudioSystemHealthMonitor.java:539)
	at com.intellij.ide.AndroidStudioSystemHealthMonitorAdapter.countActionInvocation(AndroidStudioSystemHealthMonitorAdapter.java:31)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.fireBeforeActionPerformed(ActionManagerImpl.java:1293)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:151)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:447)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:776)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Git:
```
java.lang.Throwable: Assertion failed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:180)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:189)
	at org.jetbrains.ide.BuiltInServerManagerImpl.waitForStart(BuiltInServerManagerImpl.kt:110)
	at org.jetbrains.git4idea.ssh.GitXmlRpcHandlerService.getXmlRcpPort(GitXmlRpcHandlerService.java:69)
	at git4idea.commands.GitHandlerAuthenticationManager.prepareHttpAuth(GitHandlerAuthenticationManager.java:107)
	at git4idea.commands.GitHandlerAuthenticationManager.lambda$prepare$0(GitHandlerAuthenticationManager.java:68)
	at git4idea.GitUtil.tryRunOrClose(GitUtil.java:1081)
	at git4idea.commands.GitHandlerAuthenticationManager.prepare(GitHandlerAuthenticationManager.java:67)
	at git4idea.commands.GitImplBase.run(GitImplBase.java:153)
	at git4idea.commands.GitImplBase.runCommandWithoutCollectingOutput(GitImplBase.java:92)
	at git4idea.history.GitDetailsCollector.readRecordsFromHandler(GitDetailsCollector.kt:95)
	at git4idea.history.GitDetailsCollector.readFullDetailsFromHandler(GitDetailsCollector.kt:70)
	at git4idea.history.GitDetailsCollector.readFullDetailsForHashes(GitDetailsCollector.kt:44)
	at git4idea.history.GitLogUtil.readFullDetailsForHashes(GitLogUtil.java:219)
	at git4idea.log.GitLogProvider.readFullDetails(GitLogProvider.java:331)
	at com.intellij.vcs.log.util.VcsLogUtil.getDetails(VcsLogUtil.java:206)
	at net.ntworld.mergeRequestIntegrationIde.ui.service.DisplayChangesService.findChanges(DisplayChangesService.kt:132)
	at net.ntworld.mergeRequestIntegrationIde.ui.mergeRequest.tab.commit.CommitChanges$setCommits$1.run(CommitChanges.kt:48)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by LionZXY** [comment]
Any update?

**Comment by mochadwi** [comment]
Any updates? I also using EE version for this great plugin and having the same issue.

AGP & AS: 4.0.0-beta

**Comment by nhat-phan** [comment]
Sorry it's a tricky bug. 

Since 2020.1.5 the plugin will support Android Studio v4.0.0-beta (will available for download in next 24h)
