### ISSUE TITLE
'Add comment' creates two comments and one is corrupted

### ISSUE THREAD

**Issue by Pegietix** [nhat-phan/merge-request-integration#23]
During 'Code review', when adding comment via right click -> 'add comment', after clicking 'Create' two comments are created. One is fine and the other is a copy of the first with corrupted diff:

![image](https://user-images.githubusercontent.com/37411436/73933607-16759b80-48dd-11ea-93ea-60cbf493baee.png)

**Comment by nhat-phan** [comment]
Thank for reporting the problem.

Seems it happens when the comment is not placed in the changes of code. If you see other cases, please let me know.

**Comment by s-hildebrandt** [comment]
I have the same issue when commenting on lines that have not been changed in the merge request but are in the same file.. It actually creates 3 comments.

This shows up after it fails:
![gitlab-integration](https://user-images.githubusercontent.com/6561282/74634951-476b9100-5165-11ea-82f7-f0096b9b81b8.png)

I get this error message in IntelliJ when it happens:
```
java.security.PrivilegedActionException: java.security.PrivilegedActionException: java.lang.Exception: 500 Internal Server Error
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:908)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:846)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:778)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.security.PrivilegedActionException: java.lang.Exception: 500 Internal Server Error
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	... 15 more
Caused by: java.lang.Exception: 500 Internal Server Error
	at net.ntworld.mergeRequestIntegration.provider.gitlab.commandHandler.GitlabCreateNoteCommandHandler$handle$2.invoke(GitlabCreateNoteCommandHandler.kt:28)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.commandHandler.GitlabCreateNoteCommandHandler$handle$2.invoke(GitlabCreateNoteCommandHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabClient$Companion.invoke(GitlabClient.kt:56)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.commandHandler.GitlabCreateNoteCommandHandler.handle(GitlabCreateNoteCommandHandler.kt:27)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.commandHandler.GitlabCreateNoteCommandHandler.handle(GitlabCreateNoteCommandHandler.kt:11)
	at net.ntworld.foundation.cqrs.CommandHandler$DefaultImpls.execute(CommandHandler.kt:10)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.commandHandler.GitlabCreateNoteCommandHandler.execute(GitlabCreateNoteCommandHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.LocalCommandBus.process(LocalCommandBus.kt:47)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi.tryCreateNoteCommand(GitlabCommentApi.kt:174)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi.access$tryCreateNoteCommand(GitlabCommentApi.kt:17)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi$create$1$1.invoke(GitlabCommentApi.kt:85)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi$create$1$1.invoke(GitlabCommentApi.kt:17)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi.tryCreateNoteCommand(GitlabCommentApi.kt:176)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi.access$tryCreateNoteCommand(GitlabCommentApi.kt:17)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi$create$1.invoke(GitlabCommentApi.kt:80)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi$create$1.invoke(GitlabCommentApi.kt:17)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi.tryCreateNoteCommand(GitlabCommentApi.kt:176)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabCommentApi.create(GitlabCommentApi.kt:75)
	at net.ntworld.mergeRequestIntegration.commandHandler.CreateCommentCommandHandler.handle(CreateCommentCommandHandler.kt:12)
	at net.ntworld.mergeRequestIntegration.commandHandler.CreateCommentCommandHandler.handle(CreateCommentCommandHandler.kt:9)
	at net.ntworld.foundation.cqrs.CommandHandler$DefaultImpls.execute(CommandHandler.kt:10)
	at net.ntworld.mergeRequestIntegration.commandHandler.CreateCommentCommandHandler.execute(CreateCommentCommandHandler.kt:9)
	at net.ntworld.mergeRequestIntegration.LocalCommandBus.process(LocalCommandBus.kt:47)
	at net.ntworld.mergeRequestIntegrationIde.ui.panel.CommentEditorPanel.createComment(CommentEditorPanel.kt:136)
	at net.ntworld.mergeRequestIntegrationIde.ui.panel.CommentEditorPanel.access$createComment(CommentEditorPanel.kt:25)
	at net.ntworld.mergeRequestIntegrationIde.ui.panel.CommentEditorPanel$1.actionPerformed(CommentEditorPanel.kt:82)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	... 20 more
```

Let me know if you want any other details.

**Comment by s-hildebrandt** [comment]
I just noticed that it behaves a bit differently if you are using the Unified viewer or Side-by-side viewer to review the code.

When using the Unified viewer it creates two comments instead of three as with the Side-by-side viewer.

In both cases it's also makes GitLab unable to display any comments in the merge request on the GitLab web. It shows this banner:
![gitlab-error](https://user-images.githubusercontent.com/6561282/74635928-489dbd80-5167-11ea-8d51-eaee68e14bd6.png)
