### ISSUE TITLE
No such method "VcsLogContentUtil.getOrCreateLog()" on IntelliJ EAP version

### ISSUE THREAD

**Issue by intgr** [nhat-phan/merge-request-integration#29]
I'm using IntelliJ IDEA 2020.1 EAP (build IU-201.3803.71), I assume that's the cause of the following error:

<pre>
java.lang.NoSuchMethodError: 'com.intellij.vcs.log.impl.VcsLogManager com.intellij.vcs.log.impl.VcsLogContentUtil.getOrCreateLog(com.intellij.openapi.project.Project)'
	at net.ntworld.mergeRequestIntegrationIde.ui.service.DisplayChangesService.findChanges(DisplayChangesService.kt:127)
	at net.ntworld.mergeRequestIntegrationIde.ui.mergeRequest.tab.commit.CommitChanges$setCommits$1.run(CommitChanges.kt:48)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:192)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:468)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:444)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:421)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:933)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:806)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:433)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:690)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:432)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
</pre>

**Comment by intgr** [comment]
Indeed with IntelliJ 2019.3.2 this error does not occur.

**Comment by nhat-phan** [comment]
Thank you for letting me know. I'll check and adapt the code.
