### ISSUE TITLE
Can't add or view comments

### ISSUE THREAD

**Issue by alxvgt** [nhat-phan/merge-request-integration#47]
Hello,
I've juste discover your plugin, that is jus amazing and it's a great fature that you add to a great IDE !
Thank you s much for yur work !

I have one of the latest version of Phpstorm and after the installation/configuration of your plugin, i can retrieve MRs of my project and open some diffs but unable to show/add comment in the diff view.

Here is the stack trace error fetch by Phpstorm : 

```
java.lang.NoSuchMethodError: 'void com.intellij.openapi.editor.impl.EditorEmbeddedComponentManager$Properties.<init>(com.intellij.openapi.editor.impl.EditorEmbeddedComponentManager$ResizePolicy, boolean, boolean, int, int)'
	at net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadViewImpl.initialize(ThreadViewImpl.kt:159)
	at net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadPresenterImpl.<init>(ThreadPresenterImpl.kt:38)
	at net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadFactory.makePresenter(ThreadFactory.kt:27)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.findThreadModelOnLine(AbstractDiffView.kt:232)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.displayCommentsAndEditorOnLine(AbstractDiffView.kt:158)
	at net.ntworld.mergeRequestIntegrationIde.diff.TwoSideTextDiffView.displayEditorOnLine(TwoSideTextDiffView.kt:107)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl.onGutterActionPerformed(DiffPresenterImpl.kt:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:127)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:21)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy178.onGutterActionPerformed(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.dispatchOnGutterActionPerformed(AbstractDiffView.kt:111)
	at net.ntworld.mergeRequestIntegrationIde.diff.TwoSideTextDiffView$createGutterIcons$2.invoke(TwoSideTextDiffView.kt:43)
	at net.ntworld.mergeRequestIntegrationIde.diff.TwoSideTextDiffView$createGutterIcons$2.invoke(TwoSideTextDiffView.kt:14)
	at net.ntworld.mergeRequestIntegrationIde.diff.gutter.GutterIconRendererImpl.triggerAddAction(GutterIconRendererImpl.kt:52)
	at net.ntworld.mergeRequestIntegrationIde.diff.gutter.AddCommentEditorActionBase$MyHandler.doExecute(AddCommentEditorActionBase.kt:20)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:213)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:103)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:212)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:98)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:107)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:82)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:296)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:281)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:285)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:112)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:112)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:517)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:36)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:539)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Here is my Phptorm current version :  
![image](https://user-images.githubusercontent.com/1221867/78991585-8c92ba80-7b39-11ea-9000-8ac6662e98cd.png)

I hope this helps you o improve your plugin.

**Comment by nhat-phan** [comment]
Thank you for using the plugin.

Based on the log, I guess you are using v2020.1.2 which is not compatible with IDEs version 201.*

Please ensure that the plugin version v2020.1.3eap is installed. If you cannot see version v2020.1.3eap in IDE's preference, you can go to [plugin page](https://plugins.jetbrains.com/plugin/13615-merge-request-integration-ee--code-review-for-gitlab/versions), select channel EAP, download and drag the plugin to your IDE manually.

![Screen Shot 2020-04-10 at 19 51 34](https://user-images.githubusercontent.com/34987391/79011639-bca38300-7b64-11ea-9c07-c77915c54de7.png)

**Comment by alxvgt** [comment]
Thank you for your quick answer. I confirm that all is good with the EAP version of the plugin !  
I think your work on this plugin will simplify my developer's day !
Thanks a lot !
