### ISSUE TITLE
UI frozen on changing to new file

### ISSUE THREAD

**Issue by bironran** [nhat-phan/merge-request-integration#49]
UI freeze for seconds on changing to new file. The project I'm developing on is pretty huge (files, LoC, size of each file).
I'm on the 2020.1.4eap version and IDEA 2020.1.
The new "checkout code" option on/off doesn't seem to make a difference.

IntelliJ thread dump attached.
Another log message in main log:
`2020-04-15 11:31:28,548 [ 346635]   INFO - agnostic.FrequentEventDetector - Too many events posted, #5. Event: java.awt.event.ComponentEvent[COMPONENT_RESIZED (0,0 709x0)] on net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadViewImpl$ComponentWrapper[,0,0,709x0,invalid,layout=com.intellij.ui.components.JBScrollPane$Layout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.util.ui.JBEmptyBorder@23a8705b,flags=16777536,maximumSize=,minimumSize=,preferredSize=,columnHeader=,horizontalScrollBar=com.intellij.ui.components.JBScrollBar[,0,0,0x0,hidden,alignmentX=0.0,alignmentY=0.0,border=,flags=20971520,maximumSize=,minimumSize=,preferredSize=,blockIncrement=10,orientation=HORIZONTAL,unitIncrement=1],horizontalScrollBarPolicy=HORIZONTAL_SCROLLBAR_NEVER,lowerLeft=com.intellij.ui.components.JBScrollPane$Corner[,0,0,0x0,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=],lowerRight=com.intellij.ui.components.JBScrollPane$Corner[,717,0,0x0,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=],rowHeader=,upperLeft=com.intellij.ui.components.JBScrollPane$Corner[,0,0,0x0,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=],upperRight=com.intellij.ui.components.JBScrollPane$Corner[,717,0,0x0,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=],verticalScrollBar=com.intellij.ui.components.JBScrollBar[,0,0,0x0,hidden,alignmentX=0.0,alignmentY=0.0,border=,flags=20971520,maximumSize=,minimumSize=,preferredSize=java.awt.Dimension[width=0,height=0],blockIncrement=10,orientation=VERTICAL,unitIncrement=1],verticalScrollBarPolicy=VERTICAL_SCROLLBAR_AS_NEEDED,viewport=com.intellij.ui.components.JBViewport[,0,0,717x0,layout=com.intellij.ui.components.JBViewport$1,alignmentX=0.0,alignmentY=0.0,border=,flags=25165824,maximumSize=,minimumSize=,preferredSize=,isViewSizeSet=true,lastPaintPosition=,scrollUnderway=false],viewportBorder=com.intellij.util.ui.JBEmptyBorder@23a8705b]
java.lang.Throwable
	at com.intellij.openapi.diagnostic.FrequentEventDetector.generateMessage(FrequentEventDetector.java:83)
	at com.intellij.openapi.diagnostic.FrequentEventDetector.getMessageOnEvent(FrequentEventDetector.java:62)
	at com.intellij.ide.IdeEventQueue.doPostEvent(IdeEventQueue.java:1377)
	at com.intellij.ide.IdeEventQueue.postEvent(IdeEventQueue.java:1270)
	at java.desktop/java.awt.Component.notifyNewBounds(Component.java:2450)
	at java.desktop/java.awt.Component.reshape(Component.java:2406)
	at java.desktop/javax.swing.JComponent.reshape(JComponent.java:4249)
	at java.desktop/java.awt.Component.setBounds(Component.java:2344)
	at java.desktop/java.awt.BorderLayout.layoutContainer(BorderLayout.java:843)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:748)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:746)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:745)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1900)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[threadDump-20200415-113056.txt](https://github.com/nhat-phan/merge-request-integration/files/4483109/threadDump-20200415-113056.txt)
`

**Comment by bironran** [comment]
[threadDump-20200415-113056.txt](https://github.com/nhat-phan/merge-request-integration/files/4483117/threadDump-20200415-113056.txt)

**Comment by bironran** [comment]
"inline comments" option seems to be the difference here. with inline comments turned on the UI freeze. with it turned off everything is fast again.

**Comment by nhat-phan** [comment]
Thank you for the report 👍, I'll find the way to improve performance

**Comment by bironran** [comment]
I omitted the freeze time from my original report - the UI gets frozen for a few minutes at a time (multiple freezes of 6-10 seconds). Basically I can't use inline comments at all.

**Comment by bironran** [comment]
another data point. Apparently inline comments work well. Only when the checkbox in the configuration "always display comments in diff view" is checked the UI freeze occur. For now I can work without it.

**Comment by emanguy** [comment]
+1 to this, large diffs in a merge review cause my IDE to freeze (file is 7K+ lines)

**Comment by reitzig** [comment]
I'm seeing big freezes in some (not too large) projects as well. That's on 2020.2.2

**Comment by Griizz** [comment]
Can confirm this. Once the inlinecommands are loaded and placed it runs smoothe agains, but toggling them on or off freezes my editor for up to ~60 seconds in a 1000 rows diff with only 7 comments. I really like the feature, but its not useable right now :(

**Comment by emanguy** [comment]
Update: I think semantic syntax highlighting might have something to do with the freezing. It seems like when opening a large file the variables and such don't have "special highlighting" i.e. different colors for public vs. private methods or shadowed variables. Once everything gets properly syntax highlighted it smooths out again.
