### ISSUE TITLE
Exception while opening a file in merge request review

### ISSUE THREAD

**Issue by sfaxianovic** [nhat-phan/merge-request-integration#53]
Hello, I have an issue when I open a file in code review
`java.lang.NoSuchMethodError: 'void com.intellij.openapi.editor.impl.EditorEmbeddedComponentManager$Properties.<init>(com.intellij.openapi.editor.impl.EditorEmbeddedComponentManager$ResizePolicy, boolean, boolean, int, int)'
	at net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadViewImpl.initialize(ThreadViewImpl.kt:159)
	at net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadPresenterImpl.<init>(ThreadPresenterImpl.kt:38)
	at net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadFactory.makePresenter(ThreadFactory.kt:27)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.findThreadModelOnLine(AbstractDiffView.kt:232)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.toggleCommentsOnLine(AbstractDiffView.kt:138)
	at net.ntworld.mergeRequestIntegrationIde.diff.TwoSideTextDiffView.changeCommentsVisibilityOnLine(TwoSideTextDiffView.kt:123)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl.onGutterActionPerformed(DiffPresenterImpl.kt:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:127)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:21)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy150.onGutterActionPerformed(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.changeAllCommentsVisibility(AbstractDiffView.kt:199)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.showAllComments(AbstractDiffView.kt:82)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl.onAfterRediff(DiffPresenterImpl.kt:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:127)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:21)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy150.onAfterRediff(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView$diffViewerListener$1.onAfterRediff(AbstractDiffView.kt:32)
	at com.intellij.diff.tools.util.base.DiffViewerBase.fireEvent(DiffViewerBase.java:273)
	at com.intellij.diff.tools.util.base.DiffViewerBase.lambda$null$1(DiffViewerBase.java:146)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.finish(BackgroundTaskUtil.java:110)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.executeAndTryWait(BackgroundTaskUtil.java:98)
	at com.intellij.diff.util.DiffTaskQueue.executeAndTryWait(DiffTaskQueue.java:47)
	at com.intellij.diff.tools.util.base.DiffViewerBase.rediff(DiffViewerBase.java:140)
	at com.intellij.diff.tools.util.base.DiffViewerBase.init(DiffViewerBase.java:78)
	at com.intellij.diff.impl.DiffRequestProcessor$DefaultState.init(DiffRequestProcessor.java:1227)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$null$1(DiffRequestProcessor.java:343)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:186)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$doApplyRequest$2(DiffRequestProcessor.java:339)
	at com.intellij.diff.util.DiffUtil.runPreservingFocus(DiffUtil.java:756)
	at com.intellij.diff.impl.DiffRequestProcessor.doApplyRequest(DiffRequestProcessor.java:325)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$applyRequest$0(DiffRequestProcessor.java:307)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:180)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2319)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:188)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:140)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:171)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:177)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:41)
	at com.intellij.diff.impl.DiffRequestProcessor.applyRequest(DiffRequestProcessor.java:315)
	at com.intellij.diff.impl.DiffRequestProcessor.applyRequest(DiffRequestProcessor.java:294)
	at com.intellij.diff.impl.CacheDiffRequestProcessor.lambda$null$0(CacheDiffRequestProcessor.java:115)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.finish(BackgroundTaskUtil.java:110)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$null$1(BackgroundTaskUtil.java:90)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: Key Promoter X, net.ntworld.nhat-phan.merge-request-integration-ee, Lombook Plugin, ink.organics.pojo2json, org.sonarlint.idea

**Comment by ll14m4n** [comment]
i have the same issue. 
opening  diff view  for most of the files raises the error. some files still works though....

**Comment by nhat-phan** [comment]
I've upload a new version for IDE 2020.1 (called `2020.1.5-built-for-ide-2020.1`) which contains cool features (such as open single file to review, jump to code from comment) and bug fixes.

It will be available in next 24h.
