### ISSUE TITLE
Trying to add a comment in Intellij running linux fails

### ISSUE THREAD

**Issue by JaimeFreireB3I** [nhat-phan/merge-request-integration#54]
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:30)
	at com.intellij.ui.tabs.impl.JBTabsImpl.getTabs(JBTabsImpl.java:1536)
	at com.intellij.ui.tabs.impl.JBTabsImpl.getTabCount(JBTabsImpl.java:2005)
	at com.intellij.ui.tabs.impl.singleRow.SingleRowPassInfo.<init>(SingleRowPassInfo.java:39)
	at com.intellij.ui.tabs.impl.singleRow.SingleRowLayout.layoutSingleRow(SingleRowLayout.java:101)
	at com.intellij.ui.tabs.impl.JBTabsImpl.doLayout(JBTabsImpl.java:1664)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at com.intellij.ui.tabs.impl.JBTabsImpl.revalidateAndRepaint(JBTabsImpl.java:1398)
	at com.intellij.ui.tabs.impl.JBTabsImpl.revalidateAndRepaint(JBTabsImpl.java:1381)
	at com.intellij.ui.tabs.impl.JBTabsImpl.updateText(JBTabsImpl.java:1430)
	at com.intellij.ui.tabs.impl.JBTabsImpl.propertyChange(JBTabsImpl.java:1285)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at com.intellij.ui.tabs.TabInfo.append(TabInfo.java:148)
	at com.intellij.ui.tabs.TabInfo.setText(TabInfo.java:118)
	at net.ntworld.mergeRequestIntegrationIde.ui.mergeRequest.MergeRequestDetails.setMergeRequestInfo(MergeRequestDetails.kt:210)
	at net.ntworld.mergeRequestIntegrationIde.ui.toolWindowTab.MergeRequestToolWindowTab$myCollectionListener$1.mergeRequestSelected(MergeRequestToolWindowTab.kt:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:127)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:21)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy184.mergeRequestSelected(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.ui.mergeRequest.MergeRequestCollectionTree$myTreeSelectionListener$1.valueChanged(MergeRequestCollectionTree.kt:36)
	at java.desktop/javax.swing.JTree.fireValueChanged(JTree.java:2967)
	at java.desktop/javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3456)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:641)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.clearSelection(DefaultTreeSelectionModel.java:580)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:743)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:629)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:4324)
	at java.desktop/javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeModel.java:607)
	at java.desktop/javax.swing.tree.DefaultTreeModel.nodeStructureChanged(DefaultTreeModel.java:391)
	at net.ntworld.mergeRequestIntegrationIde.ui.mergeRequest.MergeRequestCollectionTree.dataReceived(MergeRequestCollectionTree.kt:79)
	at net.ntworld.mergeRequestIntegrationIde.ui.mergeRequest.AbstractMergeRequestCollection$myListener$1.dataReceived(AbstractMergeRequestCollection.kt:67)
	at net.ntworld.mergeRequestIntegrationIde.task.SearchMergeRequestTask.run(SearchMergeRequestTask.kt:48)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:930)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:432)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:625)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:570)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by JaimeFreireB3I** [comment]
Thanks a lot for your great work with this plugin! @nhat-phan

**Comment by JaimeFreireB3I** [comment]
Thanks a lot @nhat-phan !
