### ISSUE TITLE
Error when selecting any file in the merge request

### ISSUE THREAD

**Issue by EugeneAndrosovPaser** [nhat-phan/merge-request-integration#56]
Lately, I have an error when I open a merge request. 
Version: Merge Request Integration EE - Code Review for GitLab 2020.1.2
Steps to reproduce:
1. Refresh repository list;
2. Select any in the list;
3. Select any merge request in list and press button `Code Review`;
4. Select any file in `Merge Request's Changes`;
5. In the middle window showed only error message: `Error: can't show diff`.
![screenshot](https://i.imgur.com/UukpRB4.png)

Call stacks:
```java
java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:146)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:30)
	at com.intellij.ui.tabs.impl.JBTabsImpl.getTabs(JBTabsImpl.java:1536)
	at com.intellij.ui.tabs.impl.JBTabsImpl.getTabCount(JBTabsImpl.java:2005)
	at com.intellij.ui.tabs.impl.singleRow.SingleRowPassInfo.<init>(SingleRowPassInfo.java:39)
	at com.intellij.ui.tabs.impl.singleRow.SingleRowLayout.layoutSingleRow(SingleRowLayout.java:101)
	at com.intellij.ui.tabs.impl.JBTabsImpl.doLayout(JBTabsImpl.java:1664)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at com.intellij.ui.tabs.impl.JBTabsImpl.revalidateAndRepaint(JBTabsImpl.java:1398)
	at com.intellij.ui.tabs.impl.JBTabsImpl.revalidateAndRepaint(JBTabsImpl.java:1381)
	at com.intellij.ui.tabs.impl.JBTabsImpl.updateText(JBTabsImpl.java:1430)
	at com.intellij.ui.tabs.impl.JBTabsImpl.propertyChange(JBTabsImpl.java:1285)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:341)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:333)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:266)
	at com.intellij.ui.tabs.TabInfo.append(TabInfo.java:148)
	at com.intellij.ui.tabs.TabInfo.setText(TabInfo.java:118)
	at net.ntworld.mergeRequestIntegrationIde.ui.mergeRequest.MergeRequestDetails$myGetCommitsListener$1.dataReceived(MergeRequestDetails.kt:119)
	at net.ntworld.mergeRequestIntegrationIde.task.GetCommitsTask.run(GetCommitsTask.kt:38)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
----------------
```java
java.lang.NoSuchMethodError: 'void com.intellij.openapi.editor.impl.EditorEmbeddedComponentManager$Properties.<init>(com.intellij.openapi.editor.impl.EditorEmbeddedComponentManager$ResizePolicy, boolean, boolean, int, int)'
	at net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadViewImpl.initialize(ThreadViewImpl.kt:159)
	at net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadPresenterImpl.<init>(ThreadPresenterImpl.kt:38)
	at net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadFactory.makePresenter(ThreadFactory.kt:27)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.findThreadModelOnLine(AbstractDiffView.kt:232)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.toggleCommentsOnLine(AbstractDiffView.kt:138)
	at net.ntworld.mergeRequestIntegrationIde.diff.TwoSideTextDiffView.changeCommentsVisibilityOnLine(TwoSideTextDiffView.kt:123)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl.onGutterActionPerformed(DiffPresenterImpl.kt:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:127)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:21)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy204.onGutterActionPerformed(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.changeAllCommentsVisibility(AbstractDiffView.kt:199)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.showAllComments(AbstractDiffView.kt:82)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl.onAfterRediff(DiffPresenterImpl.kt:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:127)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:21)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy204.onAfterRediff(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView$diffViewerListener$1.onAfterRediff(AbstractDiffView.kt:32)
	at com.intellij.diff.tools.util.base.DiffViewerBase.fireEvent(DiffViewerBase.java:273)
	at com.intellij.diff.tools.util.base.DiffViewerBase.lambda$null$1(DiffViewerBase.java:146)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.finish(BackgroundTaskUtil.java:110)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.executeAndTryWait(BackgroundTaskUtil.java:98)
	at com.intellij.diff.util.DiffTaskQueue.executeAndTryWait(DiffTaskQueue.java:47)
	at com.intellij.diff.tools.util.base.DiffViewerBase.rediff(DiffViewerBase.java:140)
	at com.intellij.diff.tools.util.base.DiffViewerBase.init(DiffViewerBase.java:78)
	at com.intellij.diff.impl.DiffRequestProcessor$DefaultState.init(DiffRequestProcessor.java:1227)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$null$1(DiffRequestProcessor.java:343)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:188)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$doApplyRequest$2(DiffRequestProcessor.java:339)
	at com.intellij.diff.util.DiffUtil.runPreservingFocus(DiffUtil.java:756)
	at com.intellij.diff.impl.DiffRequestProcessor.doApplyRequest(DiffRequestProcessor.java:325)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$applyRequest$0(DiffRequestProcessor.java:307)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:180)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2319)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:188)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:140)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:171)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:177)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:41)
	at com.intellij.diff.impl.DiffRequestProcessor.applyRequest(DiffRequestProcessor.java:315)
	at com.intellij.diff.impl.DiffRequestProcessor.applyRequest(DiffRequestProcessor.java:294)
	at com.intellij.diff.impl.CacheDiffRequestProcessor.lambda$null$0(CacheDiffRequestProcessor.java:115)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.finish(BackgroundTaskUtil.java:110)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$null$1(BackgroundTaskUtil.java:90)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
----------------
```java
java.lang.NoSuchMethodError: 'void com.intellij.openapi.editor.impl.EditorEmbeddedComponentManager$Properties.<init>(com.intellij.openapi.editor.impl.EditorEmbeddedComponentManager$ResizePolicy, boolean, boolean, int, int)'
	at net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadViewImpl.initialize(ThreadViewImpl.kt:159)
	at net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadPresenterImpl.<init>(ThreadPresenterImpl.kt:38)
	at net.ntworld.mergeRequestIntegrationIde.diff.thread.ThreadFactory.makePresenter(ThreadFactory.kt:27)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.findThreadModelOnLine(AbstractDiffView.kt:232)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.toggleCommentsOnLine(AbstractDiffView.kt:138)
	at net.ntworld.mergeRequestIntegrationIde.diff.TwoSideTextDiffView.changeCommentsVisibilityOnLine(TwoSideTextDiffView.kt:123)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl.onGutterActionPerformed(DiffPresenterImpl.kt:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:127)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:21)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy204.onGutterActionPerformed(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.changeAllCommentsVisibility(AbstractDiffView.kt:199)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView.showAllComments(AbstractDiffView.kt:82)
	at net.ntworld.mergeRequestIntegrationIde.diff.DiffPresenterImpl.onAfterRediff(DiffPresenterImpl.kt:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:127)
	at com.intellij.util.EventDispatcher.access$000(EventDispatcher.java:21)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy204.onAfterRediff(Unknown Source)
	at net.ntworld.mergeRequestIntegrationIde.diff.AbstractDiffView$diffViewerListener$1.onAfterRediff(AbstractDiffView.kt:32)
	at com.intellij.diff.tools.util.base.DiffViewerBase.fireEvent(DiffViewerBase.java:273)
	at com.intellij.diff.tools.util.base.DiffViewerBase.lambda$null$1(DiffViewerBase.java:146)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.finish(BackgroundTaskUtil.java:110)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.executeAndTryWait(BackgroundTaskUtil.java:98)
	at com.intellij.diff.util.DiffTaskQueue.executeAndTryWait(DiffTaskQueue.java:47)
	at com.intellij.diff.tools.util.base.DiffViewerBase.rediff(DiffViewerBase.java:140)
	at com.intellij.diff.tools.util.base.DiffViewerBase.init(DiffViewerBase.java:78)
	at com.intellij.diff.impl.DiffRequestProcessor$DefaultState.init(DiffRequestProcessor.java:1227)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$null$1(DiffRequestProcessor.java:343)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:188)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$doApplyRequest$2(DiffRequestProcessor.java:339)
	at com.intellij.diff.util.DiffUtil.runPreservingFocus(DiffUtil.java:756)
	at com.intellij.diff.impl.DiffRequestProcessor.doApplyRequest(DiffRequestProcessor.java:325)
	at com.intellij.diff.impl.DiffRequestProcessor.lambda$applyRequest$0(DiffRequestProcessor.java:307)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:180)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2319)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:188)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:140)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:171)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:177)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$null$2(FocusManagerImpl.java:185)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by nhat-phan** [comment]
Thank you for using the plugin.

I guess you are using the plugin version <= 2020.1.2, it does not support IDE 2020.1.x. Could you please update to `2020.1.5-...`, there is some cool updates which is you can review a single commit/file (don't have to click Code Review button)

**Comment by EugeneAndrosovPaser** [comment]
Thank you for the suggestion.
It's happened because Goland doesn't see this update in the plugins section, but I download the plugin manually and install it from the filesystem.
All works fine.

The issue can be closed.
