### ISSUE TITLE
Could not initialize class net.ntworld.mergeRequestIntegration.util.DateTimeUtil

### ISSUE THREAD

**Issue by mmjurov** [nhat-phan/merge-request-integration#8]
Hello there!
Thank you for the plugin. Installed it just to try, but cannot use it.
Trial version of EE edition (1st day of 30 free).
Windows 10 Pro user. 
PhpStorm 2019.3.1.
Gitlab is selfhosted on our own server with custom domain like https://gitlab.mycompany.com with ssl certificate from Letsencrypt.
Project which i try to use have protected visibility in gitlab.

Added new server into pulgin settings, checked connection - it's ok.

![image](https://user-images.githubusercontent.com/802208/72686742-d9519100-3b08-11ea-8692-424007058c40.png)

In the tools panel can see this connection and it's legal.

![image](https://user-images.githubusercontent.com/802208/72686752-f6865f80-3b08-11ea-9c87-fb465de6c792.png)

When trying to open tab with Opening MRs, PhpStorm notified about exception in the plugin with the following details:

```
java.lang.NoClassDefFoundError: Could not initialize class net.ntworld.mergeRequestIntegration.util.DateTimeUtil
	at net.ntworld.mergeRequestIntegration.provider.gitlab.transformer.GitlabMRSimpleTransformer.transform(GitlabMRSimpleTransformer.kt:18)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabMergeRequestApi.search(GitlabMergeRequestApi.kt:105)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.handle(GetMergeRequestsQueryHandler.kt:15)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.handle(GetMergeRequestsQueryHandler.kt:11)
	at net.ntworld.foundation.cqrs.QueryHandler$DefaultImpls.execute(QueryHandler.kt:10)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.execute(GetMergeRequestsQueryHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.execute(GetMergeRequestsQueryHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.LocalQueryBus.process(LocalQueryBus.kt:36)
	at net.ntworld.mergeRequestIntegrationIde.task.SearchMergeRequestTask.run(SearchMergeRequestTask.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by nhat-phan** [comment]
Hi mmjurov,

Could you please let me know whether you are using both CE & EE version on the same IDE?

**Comment by mmjurov** [comment]
Hello. Sorry for the long answer. 
No, I use only EE version. My installation flow:
- installed CE version
- noticed that I can not use selfhosted Gitlab instance
- delete CE version
- restart IDE
- install EE version
- activate it with trial version on 30 days
- restart IDE

**Comment by IVRyazanov** [comment]
Yeap, have this bag too
Last Ultimate IDEA with last version of plugin + GitLab Enterprise Edition 11.5.4-ee

And then another error:
`java.lang.ExceptionInInitializerError
	at net.ntworld.mergeRequestIntegration.provider.gitlab.transformer.GitlabMRSimpleTransformer.transform(GitlabMRSimpleTransformer.kt:18)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabMergeRequestApi.search(GitlabMergeRequestApi.kt:105)
	at net.ntworld.mergeRequestIntegration.provider.MergeRequestApiDecorator.search(MergeRequestApiDecorator.kt)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabMergeRequestApiCache.search(GitlabMergeRequestApiCache.kt:38)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.handle(GetMergeRequestsQueryHandler.kt:15)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.handle(GetMergeRequestsQueryHandler.kt:11)
	at net.ntworld.foundation.cqrs.QueryHandler$DefaultImpls.execute(QueryHandler.kt:10)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.execute(GetMergeRequestsQueryHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetMergeRequestsQueryHandler.execute(GetMergeRequestsQueryHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.LocalQueryBus.process(LocalQueryBus.kt:36)
	at net.ntworld.mergeRequestIntegrationIde.task.SearchMergeRequestTask.run(SearchMergeRequestTask.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: The datetime zone id 'GMT+03:00' is not recognised
	at org.joda.time.DateTimeZone.forID(DateTimeZone.java:247)
	at net.ntworld.mergeRequestIntegration.util.DateTimeUtil.<clinit>(DateTimeUtil.kt:24)
	... 26 more`

**Comment by IVRyazanov** [comment]
datetime zone id 'GMT+03:00' is not recognised at ....
