### ISSUE TITLE
Crash with empty avatars in GitLib

### ISSUE THREAD

**Issue by sleepyprof** [nhat-phan/merge-request-integration#93]
I had the following exception when no avatar was set in my user account in GitLab. However, even after creating an avatar this exception still happens from time to time - leaving a crashed background task "Fetching merge requests" in IntelliJ.

Here the exception:
```
java.lang.IllegalStateException: input.getAvatarUrl() must not be null
	at net.ntworld.mergeRequestIntegration.provider.gitlab.transformer.GitlabMemberTransformer.transform(GitlabMemberTransformer.kt:14)
	at net.ntworld.mergeRequestIntegration.provider.gitlab.GitlabProjectApi.getMembers(GitlabProjectApi.kt:34)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetProjectMembersQueryHandler.handle(GetProjectMembersQueryHandler.kt:17)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetProjectMembersQueryHandler.handle(GetProjectMembersQueryHandler.kt:11)
	at net.ntworld.foundation.cqrs.QueryHandler$DefaultImpls.execute(QueryHandler.kt:10)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetProjectMembersQueryHandler.execute(GetProjectMembersQueryHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.queryHandler.GetProjectMembersQueryHandler.execute(GetProjectMembersQueryHandler.kt:11)
	at net.ntworld.mergeRequestIntegration.LocalQueryBus.process(LocalQueryBus.kt:38)
	at net.ntworld.mergeRequestIntegrationIde.task.FetchProjectMembersTask.run(FetchProjectMembersTask.kt:34)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Version:
Merge Request Integration EE - Code Review for GitLab (2020.2.0-built-for-ide-2020.2.x).

**Comment by PeskovV** [comment]
same problem for me

**Comment by ctammes** [comment]
Same with me (see issue 106).

**Comment by ctammes** [comment]
Just found out: problem is solved after I assigned an avatar to my profile. I already had one on one site, but not at the other.
